#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    # File manager
    filemanager = "vimfiler"
    filetree_direction = "left"
    # Bootstrap
    bootstrap_before = "myspacevim#before"
    # Completion
    autocomplete_method = "asyncomplete"
    # Q recording mode
    windows_smartclose = ""
    default_indent = 2

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'core'
enable_smooth_scrolling = false

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "lang#c"

[[layers]]
name = "lang#python"

[[layers]]
name = "lang#kotlin"

[[layers]]
name = "lang#go"

[[layers]]
name = "lang#toml"

[[custom_plugins]]
repo = "https://github.com/sevko/vim-nand2tetris-syntax"
merged = false
